### ISSUE TITLE
Auto-generate Dash Datatype mapping with meta

### ISSUE THREAD

**Issue by i-walker** [i-walker/Arrow-Docset#11]
Let's discuss it here

**Comment by nomisRev** [comment]
@i-walker the first two steps would be to figure out what info we need to create a mapping and to make sure we can gather the required info to generate the mappings.

It's up to you if you want to split this over several tickets or not but this is what I suggest.
- [ ] List required data for mapping
- [ ] Check if we can gather required info from arrow-meta
- [ ] Write template (Start with an perfectly hand written mapping file)
- [ ] Translate template into arrow-meta DSL
- [ ] Make sure all files get generated in the correct dash folder

**Comment by i-walker** [comment]
I checked the Haskell Docset and the author used only these Docset Datatypes:
 "Class", "Module", "Type" and "Function", which seems reasonable.

For a somehow working MVP with some granularity, we can define most provided sections on the arrow page as Guides. This css-selector for that is:
```js
$$("div>h2:first-of-type:not([id*=package]) , 
div+h2:first-of-type:not([id*=package])")
```
This selector excludes the API Docs. I did not find a way to download them separately with wget, but if someone has an idea, please comment here. 

To exclude Video references
```js
$$(div>h2:first-of-type:not([id*=package]):not([id*=type])[id], 
div+h2:first-of-type:not([id*=package]):not([id*=type])[id])
```
For the initial version: I suggest keeping it simple and stick with max. 4 Doc-Datatypes.

**Comment by i-walker** [comment]
When it comes to generating a doc-set, there are multiple ways some more [time-consuming](https://kapeli.com/docsets#javadoc) than others. What we need to decide right now, at least for the time being. If we want to support the discoverabilty of all Functions and Classes (even though IntelliJ does a better Job than Dash) or just those on the arrow page. 

In my opinion, Arrow-Docset should solely leverage the arrow webpage, but I would like to hear your thoughts on this @nomisRev.

**Comment by nomisRev** [comment]
@i-walker the arrow webpage contains all important documentation, including all the documentation that you can find in the Arrow codebase (excluding internal parts) with runnable snippets.

So the arrow webpage should be the perfect candidate!
